"""vip_data

Revision ID: 1267a3caae1b
Revises: 4acb92a8f909
Create Date: 2024-06-18 00:00:02.494518

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "1267a3caae1b"
down_revision = "4acb92a8f909"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vip_storage",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("long_url", sa.TEXT(), nullable=False),
        sa.Column("short_url", sa.TEXT(), nullable=False),
        sa.Column("secret_key", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=True),
        sa.Column("number_of_clicks", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column("dt_created", postgresql.TIMESTAMP(timezone=False), server_default=sa.text("now()"), nullable=False),
        sa.Column("url_expires", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__vip_storage")),
        sa.UniqueConstraint("id", name=op.f("uq__vip_storage__id")),
    )
    op.create_index(op.f("ix__vip_storage__long_url"), "vip_storage", ["long_url"], unique=False)
    op.create_index(op.f("ix__vip_storage__secret_key"), "vip_storage", ["secret_key"], unique=True)
    op.create_index(op.f("ix__vip_storage__short_url"), "vip_storage", ["short_url"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__vip_storage__short_url"), table_name="vip_storage")
    op.drop_index(op.f("ix__vip_storage__secret_key"), table_name="vip_storage")
    op.drop_index(op.f("ix__vip_storage__long_url"), table_name="vip_storage")
    op.drop_table("vip_storage")
    # ### end Alembic commands ###
